change 'ps ax|grep ssh' code from exit to close
stdio streams may be shared with parent process.

Using exit in this example causes:

events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: This socket is closed.