repl: preventing REPL crash with inherited properties
When an inherited property is used as a REPL keyword, the REPL crashes.

    > process.version
    'v0.12.7'
    > .toString
    repl.js:706
        cmd.action.call(this, rest);
                ^
    TypeError: Cannot read property 'call' of undefined
        at REPLServer.parseREPLKeyword (repl.js:706:15)
        at REPLServer.<anonymous> (repl.js:255:16)
        at REPLServer.emit (events.js:107:17)
        at REPLServer.Interface._onLine (readline.js:214:10)
        at REPLServer.Interface._line (readline.js:553:8)
        at REPLServer.Interface._ttyWrite (readline.js:830:14)
        at ReadStream.onkeypress (readline.js:109:10)
        at ReadStream.emit (events.js:110:17)
        at readline.js:1175:14
        at Array.forEach (native)

This patch makes the internal `commands` object inherit from `null` so
that there will be no inherited properties.

    > process.version
    'v0.13.0-pre'
    > .toString
    Invalid REPL keyword
    >