#include "ev/ev.h" changed to #include "ev.h" to fix the following error
bash-3.2# node-waf build
Waf: Entering directory /calipso/node_modules/node-expat/build'
[1/2] cxx: node-expat.cc -> build/default/node-expat_1.o
In file included from /usr/local/include/node/uv.h:40,
from /usr/local/include/node/node.h:25,
from ../node-expat.cc:1:
/usr/local/include/node/uv-unix.h:27:19: error: ev/ev.h: No such file or directory
In file included from /usr/local/include/node/node.h:25,
from ../node-expat.cc:1:
/usr/local/include/node/uv.h:145: error: ‘ev_timer’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_idle’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_io’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_io’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_prepare’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_check’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_idle’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_async’ does not name a type
/usr/local/include/node/uv.h:158: error: ‘ev_timer’ does not name a type
Waf: Leaving directory/calipso/node_modules/node-expat/build'
Build failed: -> task failed (err #1): 
{task: cxx node-expat.cc -> node-expat_1.o}